### ISSUE TITLE
Installing problems (require 'org-ranker)

### ISSUE THREAD

**Issue by Ypot** [CSJ7701/org-ranker#2]
Hi

Installing with (require 'org-ranker), I get this message:
"File is missing: Cannot open load file, No such file or directory, csv"

**Comment by CSJ7701** [comment]
Ah, apologies. 
If you are installing manually, you will also need to install [csv.el](https://gitlab.com/u11/csv.el). If you are using straight.el, I believe it handles this dependency for you.

Alternatively, if you do not need the ability to import data from a csv, you can manually edit org-ranker.el to remove the dependency on csv. Be advised that the "org-ranker-import-from-csv" function will no longer work if you do this.

One of the things I have on the todo list is either removing that dependency or figuring out how to make it optional.
